name: Terraform Deploy

on:
  push:
    branches: [main]
    paths:
      - 'tf/**'
      - 'tf-test/**'
  workflow_dispatch:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.TERRAFORMEXECUTOR_AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.TERRAFORMEXECUTOR_AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORMEXECUTOR_AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TERRAFORMEXECUTOR_AZURE_TENANT_ID }}
  ARM_USE_MSI: false 
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: tf-test
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - run: terraform init -input=false
      - run: terraform plan -no-color -input=false -out=tfplan
      - run: terraform apply -auto-approve tfplan

  deploy-prod:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: tf
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - run: terraform init -input=false
      - run: terraform plan -no-color -input=false -out=tfplan
      - run: terraform apply -auto-approve tfplan